################################################################################
##################### Default Config Settings ##################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


################################################################################
##################### Used for turning alarm on ################################
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code
    # Don't require the code to arm the alarm
    code_arm_required: false
    # Arm again after triggering
    disarm_after_trigger: false
    
    disarmed:
      # Ensure the alarm can never be directly triggered when disarmed
        trigger_time: 0    

    armed_home:
      # Leave no delay between arming -> armed
        arming_time: 0
      # Leave no delay between pending -> triggered
        delay_time: 0

    armed_away:
    # Delay from arming and becoming armed, eg. to leave the house.
        arming_time: 120
        # Allow time to disarm the alarm before it triggers, eg. when arriving home
        delay_time: 30
        # Amount of time the alarm is triggered for
        trigger_time: 600
        
    armed_night:
      # Leave no delay between arming -> armed
        arming_time: 0
      # Leave no delay between pending -> triggered
        delay_time: 0
        

################################################################################
####################### Used to send email #####################################
notify_events:
    token: [token]
  
notify:
  - name: "events"
    platform: notify_events

